apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fhirest-demo.fullname" . }}-config
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: '{{ $val }}'
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fhirest-demo.fullname" . }}-logback-config
data:
  {{- if .Values.logbackXml}}
  logback.xml: |-
{{ .Values.logbackXml | indent 4 }}
  {{- end }}
