apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhirest-demo.fullname" . }}-postgres-secret
  labels:
    {{- include "fhirest-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.postgres.url | quote }}
  DB_APP_USER: {{ .Values.postgres.app.user | quote }}
  DB_APP_PASSWORD: {{ .Values.postgres.app.password | quote }}
  DB_ADMIN_USER: {{ .Values.postgres.admin.user | quote }}
  DB_ADMIN_PASSWORD: {{ .Values.postgres.admin.password | quote }}
  DB_POOL_SIZE: {{ .Values.postgres.dbPoolSize | quote }}
